export const adjectives = [
  'AI-powered',
  'Quantum-powered',
  'Eco-friendly',
  'Smart',
  'Next-gen',
  'Blockchain-based',
  'Augmented',
  'Hyperlocal',
  'Viral',
  'Futuristic',
  'Invisible',
  'Magical',
  'Decentralized',
  'Cloud-native',
  'Autonomous',
  'Nano-tech',
  'Sustainable',
  'Bio-engineered',
  'Virtual',
  'Machine-learning',
  'Serverless',
];

export const nouns = [
  'Platform',
  'App',
  'Marketplace',
  'Network',
  'Hub',
  'Studio',
  'Engine',
  'Portal',
  'Ecosystem',
  'Widget',
  'Service',
  'Lab',
  'SaaS',
  'Subscription Box',
  'Delivery App',
  'Therapy Service',
  'Social Network',
  'On-demand Service',
  'Crowdfunding Platform',
  'Analytics Tool',
  'Community Hub',
  'Streaming Service',
  'Virtual Assistant',
  'Consulting Platform',
  'Automated Service',
];

export const targets = [
  'Dogs',
  'Ghosts',
  'Ferrets',
  'Grandmas',
  'Pigeons',
  'Socks',
  'Sandwiches',
  'Tooth Fairies',
  'Pet Rocks',
  'Sleeping Cats',
  'Lost Umbrellas',
  'Singing Plants',
  'Plants',
  'Toddlers',
  'Cats',
  'Gardeners',
  'Space Travelers',
  'Angry Robots',
  'Time-traveling Hamsters',
  'Invisible Unicorns',
  'Dancing Chairs',
  'Talking Toasters',
  'Quirky Neighbors',
];
